css e commerce page
PhillipLam89/c1020-code-solutions pull request #33
Opened 2020-10-15 05:19 UTC by PhillipLam89

![image](https://user-images.githubusercontent.com/64397693/96080141-4bbe8a00-0e6b-11eb-91bf-d02e6eda819b.png)

2020-10-15 20:25 UTC, codingcodymiller requested changes
Yo dude! Your output differs from the intended output, please revise to make this as close as possible to the original example. For instance, your font family is not the font family requested, the color for your text is incorrect in multiple places, and the placement of the text in comparison to the example is off as well. Let us know if you have any questions on how to adjust this!

2020-10-16 23:10 UTC, codingcodymiller requested changes
This looks so much better, man!! I do have a question on your method of styling this though:

2020-10-16 23:10 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +  padding-right: 4rem;
What is all of the padding for the remaining CSS rules here doing for you? It is a lot of padding, and there is probably a better way 🤔

2020-11-21 18:36 UTC, thebearingedge requested changes

2020-11-21 18:36 UTC, thebearingedge commented on css-ecommerce-page/styles.css
> +  text-align: center;
Don't `text-align: center` like this, it's why you have so many random spacings for your prices.

2020-11-21 18:36 UTC, thebearingedge commented on css-ecommerce-page/styles.css
> +}
These should not be necessary. Probably will be fixed by not centering all the text.

2020-11-21 18:36 UTC, thebearingedge commented on css-ecommerce-page/styles.css
> +}
What is LV?

2020-11-22 01:34 UTC, thebearingedge approved these changes

2020-11-22 01:38 UTC, merged