css transitions
PhillipLam89/c1020-code-solutions pull request #49
Opened 2020-10-21 15:22 UTC by PhillipLam89

![image](https://user-images.githubusercontent.com/64397693/96741331-872eec00-1376-11eb-85ad-0ecd305d7a4e.png)

2020-10-21 18:00 UTC, codingcodymiller requested changes

2020-10-22 22:05 UTC, codingcodymiller requested changes

2020-10-22 22:05 UTC, codingcodymiller commented on css-transitions/styles.css
> +  background-color: blue;
No transition now?

2020-11-14 19:40 UTC, thebearingedge approved these changes

2020-11-29 04:44 UTC, merged