JS Bank Finished
PhillipLam89/c1020-code-solutions pull request #63
Opened 2020-11-04 02:01 UTC by PhillipLam89

![image](https://user-images.githubusercontent.com/64397693/98060525-a1e57400-1dfe-11eb-9887-130ef29e095f.png)

2020-11-04 23:43 UTC, codingcodymiller requested changes

2020-11-04 23:43 UTC, codingcodymiller commented on javascript-bank/account.js
> +      if (this.transactions[j].type === 'withdrawal') {
Why not do this in one loop? You have a loop above that is looping over the same thing.

2020-11-04 23:43 UTC, codingcodymiller commented on javascript-bank/account.js
> +  if (this.transactions.length === 0) {
This conditional is unnecessary. If the array is empty, the loop below would never start, which leaves you in the same situation 👍

2020-11-14 19:42 UTC, thebearingedge approved these changes

2020-11-22 02:58 UTC, merged